name: Update Security Policy

on:
  release:
    types: [created]

jobs:
  update-security-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Security Policy
        run: |
          version=$(echo "${GITHUB_REF#refs/tags/}")
          echo "Updating Security Policy for version $version"
          sed -i "6i | $version   | :white_check_mark: |" README.md
